# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/virtuoos/Broncode/jasp-desktop

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/virtuoos/Broncode/jasp-desktop

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/virtuoos/Broncode/jasp-desktop/CMakeFiles /home/virtuoos/Broncode/jasp-desktop//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/virtuoos/Broncode/jasp-desktop/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Dependencies

# Build rule for target.
Dependencies: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Dependencies
.PHONY : Dependencies

# fast build rule for target.
Dependencies/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Dependencies.dir/build.make CMakeFiles/Dependencies.dir/build
.PHONY : Dependencies/fast

#=============================================================================
# Target rules for targets named Modules

# Build rule for target.
Modules: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Modules
.PHONY : Modules

# fast build rule for target.
Modules/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Modules.dir/build.make CMakeFiles/Modules.dir/build
.PHONY : Modules/fast

#=============================================================================
# Target rules for targets named generate_qmlls_build_ini_file

# Build rule for target.
generate_qmlls_build_ini_file: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generate_qmlls_build_ini_file
.PHONY : generate_qmlls_build_ini_file

# fast build rule for target.
generate_qmlls_build_ini_file/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_qmlls_build_ini_file.dir/build.make CMakeFiles/generate_qmlls_build_ini_file.dir/build
.PHONY : generate_qmlls_build_ini_file/fast

#=============================================================================
# Target rules for targets named module_QMLComponents_aotstats_target

# Build rule for target.
module_QMLComponents_aotstats_target: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 module_QMLComponents_aotstats_target
.PHONY : module_QMLComponents_aotstats_target

# fast build rule for target.
module_QMLComponents_aotstats_target/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/module_QMLComponents_aotstats_target.dir/build.make CMakeFiles/module_QMLComponents_aotstats_target.dir/build
.PHONY : module_QMLComponents_aotstats_target/fast

#=============================================================================
# Target rules for targets named all_aotstats

# Build rule for target.
all_aotstats: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_aotstats
.PHONY : all_aotstats

# fast build rule for target.
all_aotstats/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_aotstats.dir/build.make CMakeFiles/all_aotstats.dir/build
.PHONY : all_aotstats/fast

#=============================================================================
# Target rules for targets named Common

# Build rule for target.
Common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Common
.PHONY : Common

# fast build rule for target.
Common/fast:
	$(MAKE) $(MAKESILENT) -f Common/CMakeFiles/Common.dir/build.make Common/CMakeFiles/Common.dir/build
.PHONY : Common/fast

#=============================================================================
# Target rules for targets named Common_autogen_timestamp_deps

# Build rule for target.
Common_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Common_autogen_timestamp_deps
.PHONY : Common_autogen_timestamp_deps

# fast build rule for target.
Common_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f Common/CMakeFiles/Common_autogen_timestamp_deps.dir/build.make Common/CMakeFiles/Common_autogen_timestamp_deps.dir/build
.PHONY : Common_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named Common_autogen

# Build rule for target.
Common_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Common_autogen
.PHONY : Common_autogen

# fast build rule for target.
Common_autogen/fast:
	$(MAKE) $(MAKESILENT) -f Common/CMakeFiles/Common_autogen.dir/build.make Common/CMakeFiles/Common_autogen.dir/build
.PHONY : Common_autogen/fast

#=============================================================================
# Target rules for targets named jaspResults

# Build rule for target.
jaspResults: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 jaspResults
.PHONY : jaspResults

# fast build rule for target.
jaspResults/fast:
	$(MAKE) $(MAKESILENT) -f CommonData/CMakeFiles/jaspResults.dir/build.make CommonData/CMakeFiles/jaspResults.dir/build
.PHONY : jaspResults/fast

#=============================================================================
# Target rules for targets named CommonData

# Build rule for target.
CommonData: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CommonData
.PHONY : CommonData

# fast build rule for target.
CommonData/fast:
	$(MAKE) $(MAKESILENT) -f CommonData/CMakeFiles/CommonData.dir/build.make CommonData/CMakeFiles/CommonData.dir/build
.PHONY : CommonData/fast

#=============================================================================
# Target rules for targets named CommonData_autogen_timestamp_deps

# Build rule for target.
CommonData_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CommonData_autogen_timestamp_deps
.PHONY : CommonData_autogen_timestamp_deps

# fast build rule for target.
CommonData_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CommonData/CMakeFiles/CommonData_autogen_timestamp_deps.dir/build.make CommonData/CMakeFiles/CommonData_autogen_timestamp_deps.dir/build
.PHONY : CommonData_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named CommonData_autogen

# Build rule for target.
CommonData_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CommonData_autogen
.PHONY : CommonData_autogen

# fast build rule for target.
CommonData_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CommonData/CMakeFiles/CommonData_autogen.dir/build.make CommonData/CMakeFiles/CommonData_autogen.dir/build
.PHONY : CommonData_autogen/fast

#=============================================================================
# Target rules for targets named QMLComponents

# Build rule for target.
QMLComponents: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QMLComponents
.PHONY : QMLComponents

# fast build rule for target.
QMLComponents/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/QMLComponents.dir/build.make QMLComponents/CMakeFiles/QMLComponents.dir/build
.PHONY : QMLComponents/fast

#=============================================================================
# Target rules for targets named QMLComponents_qmltyperegistration

# Build rule for target.
QMLComponents_qmltyperegistration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QMLComponents_qmltyperegistration
.PHONY : QMLComponents_qmltyperegistration

# fast build rule for target.
QMLComponents_qmltyperegistration/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/QMLComponents_qmltyperegistration.dir/build.make QMLComponents/CMakeFiles/QMLComponents_qmltyperegistration.dir/build
.PHONY : QMLComponents_qmltyperegistration/fast

#=============================================================================
# Target rules for targets named all_qmltyperegistrations

# Build rule for target.
all_qmltyperegistrations: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_qmltyperegistrations
.PHONY : all_qmltyperegistrations

# fast build rule for target.
all_qmltyperegistrations/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/all_qmltyperegistrations.dir/build.make QMLComponents/CMakeFiles/all_qmltyperegistrations.dir/build
.PHONY : all_qmltyperegistrations/fast

#=============================================================================
# Target rules for targets named QMLComponents_resources_1

# Build rule for target.
QMLComponents_resources_1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QMLComponents_resources_1
.PHONY : QMLComponents_resources_1

# fast build rule for target.
QMLComponents_resources_1/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/QMLComponents_resources_1.dir/build.make QMLComponents/CMakeFiles/QMLComponents_resources_1.dir/build
.PHONY : QMLComponents_resources_1/fast

#=============================================================================
# Target rules for targets named QMLComponentsplugin

# Build rule for target.
QMLComponentsplugin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QMLComponentsplugin
.PHONY : QMLComponentsplugin

# fast build rule for target.
QMLComponentsplugin/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/QMLComponentsplugin.dir/build.make QMLComponents/CMakeFiles/QMLComponentsplugin.dir/build
.PHONY : QMLComponentsplugin/fast

#=============================================================================
# Target rules for targets named QMLComponents_qmllint

# Build rule for target.
QMLComponents_qmllint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QMLComponents_qmllint
.PHONY : QMLComponents_qmllint

# fast build rule for target.
QMLComponents_qmllint/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/QMLComponents_qmllint.dir/build.make QMLComponents/CMakeFiles/QMLComponents_qmllint.dir/build
.PHONY : QMLComponents_qmllint/fast

#=============================================================================
# Target rules for targets named QMLComponents_qmllint_json

# Build rule for target.
QMLComponents_qmllint_json: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QMLComponents_qmllint_json
.PHONY : QMLComponents_qmllint_json

# fast build rule for target.
QMLComponents_qmllint_json/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/QMLComponents_qmllint_json.dir/build.make QMLComponents/CMakeFiles/QMLComponents_qmllint_json.dir/build
.PHONY : QMLComponents_qmllint_json/fast

#=============================================================================
# Target rules for targets named QMLComponents_qmllint_module

# Build rule for target.
QMLComponents_qmllint_module: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QMLComponents_qmllint_module
.PHONY : QMLComponents_qmllint_module

# fast build rule for target.
QMLComponents_qmllint_module/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/QMLComponents_qmllint_module.dir/build.make QMLComponents/CMakeFiles/QMLComponents_qmllint_module.dir/build
.PHONY : QMLComponents_qmllint_module/fast

#=============================================================================
# Target rules for targets named all_qmllint

# Build rule for target.
all_qmllint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_qmllint
.PHONY : all_qmllint

# fast build rule for target.
all_qmllint/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/all_qmllint.dir/build.make QMLComponents/CMakeFiles/all_qmllint.dir/build
.PHONY : all_qmllint/fast

#=============================================================================
# Target rules for targets named all_qmllint_json

# Build rule for target.
all_qmllint_json: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_qmllint_json
.PHONY : all_qmllint_json

# fast build rule for target.
all_qmllint_json/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/all_qmllint_json.dir/build.make QMLComponents/CMakeFiles/all_qmllint_json.dir/build
.PHONY : all_qmllint_json/fast

#=============================================================================
# Target rules for targets named all_qmllint_module

# Build rule for target.
all_qmllint_module: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_qmllint_module
.PHONY : all_qmllint_module

# fast build rule for target.
all_qmllint_module/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/all_qmllint_module.dir/build.make QMLComponents/CMakeFiles/all_qmllint_module.dir/build
.PHONY : all_qmllint_module/fast

#=============================================================================
# Target rules for targets named dump_qml_context_properties

# Build rule for target.
dump_qml_context_properties: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dump_qml_context_properties
.PHONY : dump_qml_context_properties

# fast build rule for target.
dump_qml_context_properties/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/dump_qml_context_properties.dir/build.make QMLComponents/CMakeFiles/dump_qml_context_properties.dir/build
.PHONY : dump_qml_context_properties/fast

#=============================================================================
# Target rules for targets named clean_qml_context_properties

# Build rule for target.
clean_qml_context_properties: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean_qml_context_properties
.PHONY : clean_qml_context_properties

# fast build rule for target.
clean_qml_context_properties/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/clean_qml_context_properties.dir/build.make QMLComponents/CMakeFiles/clean_qml_context_properties.dir/build
.PHONY : clean_qml_context_properties/fast

#=============================================================================
# Target rules for targets named QMLComponents_resources_2

# Build rule for target.
QMLComponents_resources_2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QMLComponents_resources_2
.PHONY : QMLComponents_resources_2

# fast build rule for target.
QMLComponents_resources_2/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/QMLComponents_resources_2.dir/build.make QMLComponents/CMakeFiles/QMLComponents_resources_2.dir/build
.PHONY : QMLComponents_resources_2/fast

#=============================================================================
# Target rules for targets named QMLComponents_resources_3

# Build rule for target.
QMLComponents_resources_3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QMLComponents_resources_3
.PHONY : QMLComponents_resources_3

# fast build rule for target.
QMLComponents_resources_3/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/QMLComponents_resources_3.dir/build.make QMLComponents/CMakeFiles/QMLComponents_resources_3.dir/build
.PHONY : QMLComponents_resources_3/fast

#=============================================================================
# Target rules for targets named QMLComponents_copy_qml

# Build rule for target.
QMLComponents_copy_qml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QMLComponents_copy_qml
.PHONY : QMLComponents_copy_qml

# fast build rule for target.
QMLComponents_copy_qml/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/QMLComponents_copy_qml.dir/build.make QMLComponents/CMakeFiles/QMLComponents_copy_qml.dir/build
.PHONY : QMLComponents_copy_qml/fast

#=============================================================================
# Target rules for targets named QMLComponents_copy_res

# Build rule for target.
QMLComponents_copy_res: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QMLComponents_copy_res
.PHONY : QMLComponents_copy_res

# fast build rule for target.
QMLComponents_copy_res/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/QMLComponents_copy_res.dir/build.make QMLComponents/CMakeFiles/QMLComponents_copy_res.dir/build
.PHONY : QMLComponents_copy_res/fast

#=============================================================================
# Target rules for targets named QMLComponentsplugin_init

# Build rule for target.
QMLComponentsplugin_init: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QMLComponentsplugin_init
.PHONY : QMLComponentsplugin_init

# fast build rule for target.
QMLComponentsplugin_init/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/QMLComponentsplugin_init.dir/build.make QMLComponents/CMakeFiles/QMLComponentsplugin_init.dir/build
.PHONY : QMLComponentsplugin_init/fast

#=============================================================================
# Target rules for targets named QMLComponents_autogen_timestamp_deps

# Build rule for target.
QMLComponents_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QMLComponents_autogen_timestamp_deps
.PHONY : QMLComponents_autogen_timestamp_deps

# fast build rule for target.
QMLComponents_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/QMLComponents_autogen_timestamp_deps.dir/build.make QMLComponents/CMakeFiles/QMLComponents_autogen_timestamp_deps.dir/build
.PHONY : QMLComponents_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named QMLComponents_autogen

# Build rule for target.
QMLComponents_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QMLComponents_autogen
.PHONY : QMLComponents_autogen

# fast build rule for target.
QMLComponents_autogen/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/QMLComponents_autogen.dir/build.make QMLComponents/CMakeFiles/QMLComponents_autogen.dir/build
.PHONY : QMLComponents_autogen/fast

#=============================================================================
# Target rules for targets named QMLComponentsplugin_autogen_timestamp_deps

# Build rule for target.
QMLComponentsplugin_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QMLComponentsplugin_autogen_timestamp_deps
.PHONY : QMLComponentsplugin_autogen_timestamp_deps

# fast build rule for target.
QMLComponentsplugin_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/QMLComponentsplugin_autogen_timestamp_deps.dir/build.make QMLComponents/CMakeFiles/QMLComponentsplugin_autogen_timestamp_deps.dir/build
.PHONY : QMLComponentsplugin_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named QMLComponentsplugin_autogen

# Build rule for target.
QMLComponentsplugin_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QMLComponentsplugin_autogen
.PHONY : QMLComponentsplugin_autogen

# fast build rule for target.
QMLComponentsplugin_autogen/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/QMLComponentsplugin_autogen.dir/build.make QMLComponents/CMakeFiles/QMLComponentsplugin_autogen.dir/build
.PHONY : QMLComponentsplugin_autogen/fast

#=============================================================================
# Target rules for targets named QMLComponentsplugin_init_autogen_timestamp_deps

# Build rule for target.
QMLComponentsplugin_init_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QMLComponentsplugin_init_autogen_timestamp_deps
.PHONY : QMLComponentsplugin_init_autogen_timestamp_deps

# fast build rule for target.
QMLComponentsplugin_init_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/QMLComponentsplugin_init_autogen_timestamp_deps.dir/build.make QMLComponents/CMakeFiles/QMLComponentsplugin_init_autogen_timestamp_deps.dir/build
.PHONY : QMLComponentsplugin_init_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named QMLComponentsplugin_init_autogen

# Build rule for target.
QMLComponentsplugin_init_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 QMLComponentsplugin_init_autogen
.PHONY : QMLComponentsplugin_init_autogen

# fast build rule for target.
QMLComponentsplugin_init_autogen/fast:
	$(MAKE) $(MAKESILENT) -f QMLComponents/CMakeFiles/QMLComponentsplugin_init_autogen.dir/build.make QMLComponents/CMakeFiles/QMLComponentsplugin_init_autogen.dir/build
.PHONY : QMLComponentsplugin_init_autogen/fast

#=============================================================================
# Target rules for targets named SyntaxInterface

# Build rule for target.
SyntaxInterface: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SyntaxInterface
.PHONY : SyntaxInterface

# fast build rule for target.
SyntaxInterface/fast:
	$(MAKE) $(MAKESILENT) -f SyntaxInterface/CMakeFiles/SyntaxInterface.dir/build.make SyntaxInterface/CMakeFiles/SyntaxInterface.dir/build
.PHONY : SyntaxInterface/fast

#=============================================================================
# Target rules for targets named SyntaxInterface_other_files

# Build rule for target.
SyntaxInterface_other_files: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SyntaxInterface_other_files
.PHONY : SyntaxInterface_other_files

# fast build rule for target.
SyntaxInterface_other_files/fast:
	$(MAKE) $(MAKESILENT) -f SyntaxInterface/CMakeFiles/SyntaxInterface_other_files.dir/build.make SyntaxInterface/CMakeFiles/SyntaxInterface_other_files.dir/build
.PHONY : SyntaxInterface_other_files/fast

#=============================================================================
# Target rules for targets named SyntaxInterface_autogen_timestamp_deps

# Build rule for target.
SyntaxInterface_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SyntaxInterface_autogen_timestamp_deps
.PHONY : SyntaxInterface_autogen_timestamp_deps

# fast build rule for target.
SyntaxInterface_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f SyntaxInterface/CMakeFiles/SyntaxInterface_autogen_timestamp_deps.dir/build.make SyntaxInterface/CMakeFiles/SyntaxInterface_autogen_timestamp_deps.dir/build
.PHONY : SyntaxInterface_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named SyntaxInterface_autogen

# Build rule for target.
SyntaxInterface_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SyntaxInterface_autogen
.PHONY : SyntaxInterface_autogen

# fast build rule for target.
SyntaxInterface_autogen/fast:
	$(MAKE) $(MAKESILENT) -f SyntaxInterface/CMakeFiles/SyntaxInterface_autogen.dir/build.make SyntaxInterface/CMakeFiles/SyntaxInterface_autogen.dir/build
.PHONY : SyntaxInterface_autogen/fast

#=============================================================================
# Target rules for targets named R-Interface

# Build rule for target.
R-Interface: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 R-Interface
.PHONY : R-Interface

# fast build rule for target.
R-Interface/fast:
	$(MAKE) $(MAKESILENT) -f R-Interface/CMakeFiles/R-Interface.dir/build.make R-Interface/CMakeFiles/R-Interface.dir/build
.PHONY : R-Interface/fast

#=============================================================================
# Target rules for targets named R-InterfaceNoRInside

# Build rule for target.
R-InterfaceNoRInside: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 R-InterfaceNoRInside
.PHONY : R-InterfaceNoRInside

# fast build rule for target.
R-InterfaceNoRInside/fast:
	$(MAKE) $(MAKESILENT) -f R-Interface/CMakeFiles/R-InterfaceNoRInside.dir/build.make R-Interface/CMakeFiles/R-InterfaceNoRInside.dir/build
.PHONY : R-InterfaceNoRInside/fast

#=============================================================================
# Target rules for targets named R-Interface_autogen_timestamp_deps

# Build rule for target.
R-Interface_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 R-Interface_autogen_timestamp_deps
.PHONY : R-Interface_autogen_timestamp_deps

# fast build rule for target.
R-Interface_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f R-Interface/CMakeFiles/R-Interface_autogen_timestamp_deps.dir/build.make R-Interface/CMakeFiles/R-Interface_autogen_timestamp_deps.dir/build
.PHONY : R-Interface_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named R-Interface_autogen

# Build rule for target.
R-Interface_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 R-Interface_autogen
.PHONY : R-Interface_autogen

# fast build rule for target.
R-Interface_autogen/fast:
	$(MAKE) $(MAKESILENT) -f R-Interface/CMakeFiles/R-Interface_autogen.dir/build.make R-Interface/CMakeFiles/R-Interface_autogen.dir/build
.PHONY : R-Interface_autogen/fast

#=============================================================================
# Target rules for targets named R-InterfaceNoRInside_autogen_timestamp_deps

# Build rule for target.
R-InterfaceNoRInside_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 R-InterfaceNoRInside_autogen_timestamp_deps
.PHONY : R-InterfaceNoRInside_autogen_timestamp_deps

# fast build rule for target.
R-InterfaceNoRInside_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f R-Interface/CMakeFiles/R-InterfaceNoRInside_autogen_timestamp_deps.dir/build.make R-Interface/CMakeFiles/R-InterfaceNoRInside_autogen_timestamp_deps.dir/build
.PHONY : R-InterfaceNoRInside_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named R-InterfaceNoRInside_autogen

# Build rule for target.
R-InterfaceNoRInside_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 R-InterfaceNoRInside_autogen
.PHONY : R-InterfaceNoRInside_autogen

# fast build rule for target.
R-InterfaceNoRInside_autogen/fast:
	$(MAKE) $(MAKESILENT) -f R-Interface/CMakeFiles/R-InterfaceNoRInside_autogen.dir/build.make R-Interface/CMakeFiles/R-InterfaceNoRInside_autogen.dir/build
.PHONY : R-InterfaceNoRInside_autogen/fast

#=============================================================================
# Target rules for targets named JASPEngine

# Build rule for target.
JASPEngine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPEngine
.PHONY : JASPEngine

# fast build rule for target.
JASPEngine/fast:
	$(MAKE) $(MAKESILENT) -f Engine/CMakeFiles/JASPEngine.dir/build.make Engine/CMakeFiles/JASPEngine.dir/build
.PHONY : JASPEngine/fast

#=============================================================================
# Target rules for targets named JASPEngine_autogen_timestamp_deps

# Build rule for target.
JASPEngine_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPEngine_autogen_timestamp_deps
.PHONY : JASPEngine_autogen_timestamp_deps

# fast build rule for target.
JASPEngine_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f Engine/CMakeFiles/JASPEngine_autogen_timestamp_deps.dir/build.make Engine/CMakeFiles/JASPEngine_autogen_timestamp_deps.dir/build
.PHONY : JASPEngine_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named JASPEngine_autogen

# Build rule for target.
JASPEngine_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPEngine_autogen
.PHONY : JASPEngine_autogen

# fast build rule for target.
JASPEngine_autogen/fast:
	$(MAKE) $(MAKESILENT) -f Engine/CMakeFiles/JASPEngine_autogen.dir/build.make Engine/CMakeFiles/JASPEngine_autogen.dir/build
.PHONY : JASPEngine_autogen/fast

#=============================================================================
# Target rules for targets named JASPDesktopLib

# Build rule for target.
JASPDesktopLib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPDesktopLib
.PHONY : JASPDesktopLib

# fast build rule for target.
JASPDesktopLib/fast:
	$(MAKE) $(MAKESILENT) -f Desktop/CMakeFiles/JASPDesktopLib.dir/build.make Desktop/CMakeFiles/JASPDesktopLib.dir/build
.PHONY : JASPDesktopLib/fast

#=============================================================================
# Target rules for targets named JASP

# Build rule for target.
JASP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASP
.PHONY : JASP

# fast build rule for target.
JASP/fast:
	$(MAKE) $(MAKESILENT) -f Desktop/CMakeFiles/JASP.dir/build.make Desktop/CMakeFiles/JASP.dir/build
.PHONY : JASP/fast

#=============================================================================
# Target rules for targets named JASPDesktopLib_resources_1

# Build rule for target.
JASPDesktopLib_resources_1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPDesktopLib_resources_1
.PHONY : JASPDesktopLib_resources_1

# fast build rule for target.
JASPDesktopLib_resources_1/fast:
	$(MAKE) $(MAKESILENT) -f Desktop/CMakeFiles/JASPDesktopLib_resources_1.dir/build.make Desktop/CMakeFiles/JASPDesktopLib_resources_1.dir/build
.PHONY : JASPDesktopLib_resources_1/fast

#=============================================================================
# Target rules for targets named JASPDesktopLib_resources_2

# Build rule for target.
JASPDesktopLib_resources_2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPDesktopLib_resources_2
.PHONY : JASPDesktopLib_resources_2

# fast build rule for target.
JASPDesktopLib_resources_2/fast:
	$(MAKE) $(MAKESILENT) -f Desktop/CMakeFiles/JASPDesktopLib_resources_2.dir/build.make Desktop/CMakeFiles/JASPDesktopLib_resources_2.dir/build
.PHONY : JASPDesktopLib_resources_2/fast

#=============================================================================
# Target rules for targets named JASPDesktopLib_resources_3

# Build rule for target.
JASPDesktopLib_resources_3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPDesktopLib_resources_3
.PHONY : JASPDesktopLib_resources_3

# fast build rule for target.
JASPDesktopLib_resources_3/fast:
	$(MAKE) $(MAKESILENT) -f Desktop/CMakeFiles/JASPDesktopLib_resources_3.dir/build.make Desktop/CMakeFiles/JASPDesktopLib_resources_3.dir/build
.PHONY : JASPDesktopLib_resources_3/fast

#=============================================================================
# Target rules for targets named JASPDesktopLib_resources_4

# Build rule for target.
JASPDesktopLib_resources_4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPDesktopLib_resources_4
.PHONY : JASPDesktopLib_resources_4

# fast build rule for target.
JASPDesktopLib_resources_4/fast:
	$(MAKE) $(MAKESILENT) -f Desktop/CMakeFiles/JASPDesktopLib_resources_4.dir/build.make Desktop/CMakeFiles/JASPDesktopLib_resources_4.dir/build
.PHONY : JASPDesktopLib_resources_4/fast

#=============================================================================
# Target rules for targets named JASP_qmlimportscan

# Build rule for target.
JASP_qmlimportscan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASP_qmlimportscan
.PHONY : JASP_qmlimportscan

# fast build rule for target.
JASP_qmlimportscan/fast:
	$(MAKE) $(MAKESILENT) -f Desktop/CMakeFiles/JASP_qmlimportscan.dir/build.make Desktop/CMakeFiles/JASP_qmlimportscan.dir/build
.PHONY : JASP_qmlimportscan/fast

#=============================================================================
# Target rules for targets named JASPDesktopLib_autogen_timestamp_deps

# Build rule for target.
JASPDesktopLib_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPDesktopLib_autogen_timestamp_deps
.PHONY : JASPDesktopLib_autogen_timestamp_deps

# fast build rule for target.
JASPDesktopLib_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f Desktop/CMakeFiles/JASPDesktopLib_autogen_timestamp_deps.dir/build.make Desktop/CMakeFiles/JASPDesktopLib_autogen_timestamp_deps.dir/build
.PHONY : JASPDesktopLib_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named JASPDesktopLib_autogen

# Build rule for target.
JASPDesktopLib_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPDesktopLib_autogen
.PHONY : JASPDesktopLib_autogen

# fast build rule for target.
JASPDesktopLib_autogen/fast:
	$(MAKE) $(MAKESILENT) -f Desktop/CMakeFiles/JASPDesktopLib_autogen.dir/build.make Desktop/CMakeFiles/JASPDesktopLib_autogen.dir/build
.PHONY : JASPDesktopLib_autogen/fast

#=============================================================================
# Target rules for targets named JASP_autogen_timestamp_deps

# Build rule for target.
JASP_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASP_autogen_timestamp_deps
.PHONY : JASP_autogen_timestamp_deps

# fast build rule for target.
JASP_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f Desktop/CMakeFiles/JASP_autogen_timestamp_deps.dir/build.make Desktop/CMakeFiles/JASP_autogen_timestamp_deps.dir/build
.PHONY : JASP_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named JASP_autogen

# Build rule for target.
JASP_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASP_autogen
.PHONY : JASP_autogen

# fast build rule for target.
JASP_autogen/fast:
	$(MAKE) $(MAKESILENT) -f Desktop/CMakeFiles/JASP_autogen.dir/build.make Desktop/CMakeFiles/JASP_autogen.dir/build
.PHONY : JASP_autogen/fast

#=============================================================================
# Target rules for targets named JASPTest

# Build rule for target.
JASPTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPTest
.PHONY : JASPTest

# fast build rule for target.
JASPTest/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPTest.dir/build.make Tests/CMakeFiles/JASPTest.dir/build
.PHONY : JASPTest/fast

#=============================================================================
# Target rules for targets named JASPTestSync

# Build rule for target.
JASPTestSync: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPTestSync
.PHONY : JASPTestSync

# fast build rule for target.
JASPTestSync/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPTestSync.dir/build.make Tests/CMakeFiles/JASPTestSync.dir/build
.PHONY : JASPTestSync/fast

#=============================================================================
# Target rules for targets named JASPTestDebugData

# Build rule for target.
JASPTestDebugData: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPTestDebugData
.PHONY : JASPTestDebugData

# fast build rule for target.
JASPTestDebugData/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPTestDebugData.dir/build.make Tests/CMakeFiles/JASPTestDebugData.dir/build
.PHONY : JASPTestDebugData/fast

#=============================================================================
# Target rules for targets named JASPTestEngine

# Build rule for target.
JASPTestEngine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPTestEngine
.PHONY : JASPTestEngine

# fast build rule for target.
JASPTestEngine/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPTestEngine.dir/build.make Tests/CMakeFiles/JASPTestEngine.dir/build
.PHONY : JASPTestEngine/fast

#=============================================================================
# Target rules for targets named JASPQuickTest

# Build rule for target.
JASPQuickTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPQuickTest
.PHONY : JASPQuickTest

# fast build rule for target.
JASPQuickTest/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPQuickTest.dir/build.make Tests/CMakeFiles/JASPQuickTest.dir/build
.PHONY : JASPQuickTest/fast

#=============================================================================
# Target rules for targets named JASPTestCsvPrev

# Build rule for target.
JASPTestCsvPrev: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPTestCsvPrev
.PHONY : JASPTestCsvPrev

# fast build rule for target.
JASPTestCsvPrev/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPTestCsvPrev.dir/build.make Tests/CMakeFiles/JASPTestCsvPrev.dir/build
.PHONY : JASPTestCsvPrev/fast

#=============================================================================
# Target rules for targets named JASPTest_qmlimportscan

# Build rule for target.
JASPTest_qmlimportscan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPTest_qmlimportscan
.PHONY : JASPTest_qmlimportscan

# fast build rule for target.
JASPTest_qmlimportscan/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPTest_qmlimportscan.dir/build.make Tests/CMakeFiles/JASPTest_qmlimportscan.dir/build
.PHONY : JASPTest_qmlimportscan/fast

#=============================================================================
# Target rules for targets named JASPTestSync_qmlimportscan

# Build rule for target.
JASPTestSync_qmlimportscan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPTestSync_qmlimportscan
.PHONY : JASPTestSync_qmlimportscan

# fast build rule for target.
JASPTestSync_qmlimportscan/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPTestSync_qmlimportscan.dir/build.make Tests/CMakeFiles/JASPTestSync_qmlimportscan.dir/build
.PHONY : JASPTestSync_qmlimportscan/fast

#=============================================================================
# Target rules for targets named JASPTestDebugData_qmlimportscan

# Build rule for target.
JASPTestDebugData_qmlimportscan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPTestDebugData_qmlimportscan
.PHONY : JASPTestDebugData_qmlimportscan

# fast build rule for target.
JASPTestDebugData_qmlimportscan/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPTestDebugData_qmlimportscan.dir/build.make Tests/CMakeFiles/JASPTestDebugData_qmlimportscan.dir/build
.PHONY : JASPTestDebugData_qmlimportscan/fast

#=============================================================================
# Target rules for targets named JASPTestEngine_qmlimportscan

# Build rule for target.
JASPTestEngine_qmlimportscan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPTestEngine_qmlimportscan
.PHONY : JASPTestEngine_qmlimportscan

# fast build rule for target.
JASPTestEngine_qmlimportscan/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPTestEngine_qmlimportscan.dir/build.make Tests/CMakeFiles/JASPTestEngine_qmlimportscan.dir/build
.PHONY : JASPTestEngine_qmlimportscan/fast

#=============================================================================
# Target rules for targets named JASPQuickTest_qmlimportscan

# Build rule for target.
JASPQuickTest_qmlimportscan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPQuickTest_qmlimportscan
.PHONY : JASPQuickTest_qmlimportscan

# fast build rule for target.
JASPQuickTest_qmlimportscan/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPQuickTest_qmlimportscan.dir/build.make Tests/CMakeFiles/JASPQuickTest_qmlimportscan.dir/build
.PHONY : JASPQuickTest_qmlimportscan/fast

#=============================================================================
# Target rules for targets named JASPTestCsvPrev_qmlimportscan

# Build rule for target.
JASPTestCsvPrev_qmlimportscan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPTestCsvPrev_qmlimportscan
.PHONY : JASPTestCsvPrev_qmlimportscan

# fast build rule for target.
JASPTestCsvPrev_qmlimportscan/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPTestCsvPrev_qmlimportscan.dir/build.make Tests/CMakeFiles/JASPTestCsvPrev_qmlimportscan.dir/build
.PHONY : JASPTestCsvPrev_qmlimportscan/fast

#=============================================================================
# Target rules for targets named JASPTest_autogen_timestamp_deps

# Build rule for target.
JASPTest_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPTest_autogen_timestamp_deps
.PHONY : JASPTest_autogen_timestamp_deps

# fast build rule for target.
JASPTest_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPTest_autogen_timestamp_deps.dir/build.make Tests/CMakeFiles/JASPTest_autogen_timestamp_deps.dir/build
.PHONY : JASPTest_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named JASPTest_autogen

# Build rule for target.
JASPTest_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPTest_autogen
.PHONY : JASPTest_autogen

# fast build rule for target.
JASPTest_autogen/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPTest_autogen.dir/build.make Tests/CMakeFiles/JASPTest_autogen.dir/build
.PHONY : JASPTest_autogen/fast

#=============================================================================
# Target rules for targets named JASPTestSync_autogen_timestamp_deps

# Build rule for target.
JASPTestSync_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPTestSync_autogen_timestamp_deps
.PHONY : JASPTestSync_autogen_timestamp_deps

# fast build rule for target.
JASPTestSync_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPTestSync_autogen_timestamp_deps.dir/build.make Tests/CMakeFiles/JASPTestSync_autogen_timestamp_deps.dir/build
.PHONY : JASPTestSync_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named JASPTestSync_autogen

# Build rule for target.
JASPTestSync_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPTestSync_autogen
.PHONY : JASPTestSync_autogen

# fast build rule for target.
JASPTestSync_autogen/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPTestSync_autogen.dir/build.make Tests/CMakeFiles/JASPTestSync_autogen.dir/build
.PHONY : JASPTestSync_autogen/fast

#=============================================================================
# Target rules for targets named JASPTestDebugData_autogen_timestamp_deps

# Build rule for target.
JASPTestDebugData_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPTestDebugData_autogen_timestamp_deps
.PHONY : JASPTestDebugData_autogen_timestamp_deps

# fast build rule for target.
JASPTestDebugData_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPTestDebugData_autogen_timestamp_deps.dir/build.make Tests/CMakeFiles/JASPTestDebugData_autogen_timestamp_deps.dir/build
.PHONY : JASPTestDebugData_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named JASPTestDebugData_autogen

# Build rule for target.
JASPTestDebugData_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPTestDebugData_autogen
.PHONY : JASPTestDebugData_autogen

# fast build rule for target.
JASPTestDebugData_autogen/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPTestDebugData_autogen.dir/build.make Tests/CMakeFiles/JASPTestDebugData_autogen.dir/build
.PHONY : JASPTestDebugData_autogen/fast

#=============================================================================
# Target rules for targets named JASPTestEngine_autogen_timestamp_deps

# Build rule for target.
JASPTestEngine_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPTestEngine_autogen_timestamp_deps
.PHONY : JASPTestEngine_autogen_timestamp_deps

# fast build rule for target.
JASPTestEngine_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPTestEngine_autogen_timestamp_deps.dir/build.make Tests/CMakeFiles/JASPTestEngine_autogen_timestamp_deps.dir/build
.PHONY : JASPTestEngine_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named JASPTestEngine_autogen

# Build rule for target.
JASPTestEngine_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPTestEngine_autogen
.PHONY : JASPTestEngine_autogen

# fast build rule for target.
JASPTestEngine_autogen/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPTestEngine_autogen.dir/build.make Tests/CMakeFiles/JASPTestEngine_autogen.dir/build
.PHONY : JASPTestEngine_autogen/fast

#=============================================================================
# Target rules for targets named JASPQuickTest_autogen_timestamp_deps

# Build rule for target.
JASPQuickTest_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPQuickTest_autogen_timestamp_deps
.PHONY : JASPQuickTest_autogen_timestamp_deps

# fast build rule for target.
JASPQuickTest_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPQuickTest_autogen_timestamp_deps.dir/build.make Tests/CMakeFiles/JASPQuickTest_autogen_timestamp_deps.dir/build
.PHONY : JASPQuickTest_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named JASPQuickTest_autogen

# Build rule for target.
JASPQuickTest_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPQuickTest_autogen
.PHONY : JASPQuickTest_autogen

# fast build rule for target.
JASPQuickTest_autogen/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPQuickTest_autogen.dir/build.make Tests/CMakeFiles/JASPQuickTest_autogen.dir/build
.PHONY : JASPQuickTest_autogen/fast

#=============================================================================
# Target rules for targets named JASPTestCsvPrev_autogen_timestamp_deps

# Build rule for target.
JASPTestCsvPrev_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPTestCsvPrev_autogen_timestamp_deps
.PHONY : JASPTestCsvPrev_autogen_timestamp_deps

# fast build rule for target.
JASPTestCsvPrev_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPTestCsvPrev_autogen_timestamp_deps.dir/build.make Tests/CMakeFiles/JASPTestCsvPrev_autogen_timestamp_deps.dir/build
.PHONY : JASPTestCsvPrev_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named JASPTestCsvPrev_autogen

# Build rule for target.
JASPTestCsvPrev_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JASPTestCsvPrev_autogen
.PHONY : JASPTestCsvPrev_autogen

# fast build rule for target.
JASPTestCsvPrev_autogen/fast:
	$(MAKE) $(MAKESILENT) -f Tests/CMakeFiles/JASPTestCsvPrev_autogen.dir/build.make Tests/CMakeFiles/JASPTestCsvPrev_autogen.dir/build
.PHONY : JASPTestCsvPrev_autogen/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... CommonData_autogen"
	@echo "... CommonData_autogen_timestamp_deps"
	@echo "... Common_autogen"
	@echo "... Common_autogen_timestamp_deps"
	@echo "... Dependencies"
	@echo "... JASPDesktopLib_autogen"
	@echo "... JASPDesktopLib_autogen_timestamp_deps"
	@echo "... JASPEngine_autogen"
	@echo "... JASPEngine_autogen_timestamp_deps"
	@echo "... JASPQuickTest_autogen"
	@echo "... JASPQuickTest_autogen_timestamp_deps"
	@echo "... JASPQuickTest_qmlimportscan"
	@echo "... JASPTestCsvPrev_autogen"
	@echo "... JASPTestCsvPrev_autogen_timestamp_deps"
	@echo "... JASPTestCsvPrev_qmlimportscan"
	@echo "... JASPTestDebugData_autogen"
	@echo "... JASPTestDebugData_autogen_timestamp_deps"
	@echo "... JASPTestDebugData_qmlimportscan"
	@echo "... JASPTestEngine_autogen"
	@echo "... JASPTestEngine_autogen_timestamp_deps"
	@echo "... JASPTestEngine_qmlimportscan"
	@echo "... JASPTestSync_autogen"
	@echo "... JASPTestSync_autogen_timestamp_deps"
	@echo "... JASPTestSync_qmlimportscan"
	@echo "... JASPTest_autogen"
	@echo "... JASPTest_autogen_timestamp_deps"
	@echo "... JASPTest_qmlimportscan"
	@echo "... JASP_autogen"
	@echo "... JASP_autogen_timestamp_deps"
	@echo "... JASP_qmlimportscan"
	@echo "... Modules"
	@echo "... QMLComponents_autogen"
	@echo "... QMLComponents_autogen_timestamp_deps"
	@echo "... QMLComponents_copy_qml"
	@echo "... QMLComponents_copy_res"
	@echo "... QMLComponents_qmllint"
	@echo "... QMLComponents_qmllint_json"
	@echo "... QMLComponents_qmllint_module"
	@echo "... QMLComponents_qmltyperegistration"
	@echo "... QMLComponentsplugin_autogen"
	@echo "... QMLComponentsplugin_autogen_timestamp_deps"
	@echo "... QMLComponentsplugin_init_autogen"
	@echo "... QMLComponentsplugin_init_autogen_timestamp_deps"
	@echo "... R-InterfaceNoRInside_autogen"
	@echo "... R-InterfaceNoRInside_autogen_timestamp_deps"
	@echo "... R-Interface_autogen"
	@echo "... R-Interface_autogen_timestamp_deps"
	@echo "... SyntaxInterface_autogen"
	@echo "... SyntaxInterface_autogen_timestamp_deps"
	@echo "... SyntaxInterface_other_files"
	@echo "... all_aotstats"
	@echo "... all_qmllint"
	@echo "... all_qmllint_json"
	@echo "... all_qmllint_module"
	@echo "... all_qmltyperegistrations"
	@echo "... clean_qml_context_properties"
	@echo "... dump_qml_context_properties"
	@echo "... generate_qmlls_build_ini_file"
	@echo "... jaspResults"
	@echo "... module_QMLComponents_aotstats_target"
	@echo "... Common"
	@echo "... CommonData"
	@echo "... JASP"
	@echo "... JASPDesktopLib"
	@echo "... JASPDesktopLib_resources_1"
	@echo "... JASPDesktopLib_resources_2"
	@echo "... JASPDesktopLib_resources_3"
	@echo "... JASPDesktopLib_resources_4"
	@echo "... JASPEngine"
	@echo "... JASPQuickTest"
	@echo "... JASPTest"
	@echo "... JASPTestCsvPrev"
	@echo "... JASPTestDebugData"
	@echo "... JASPTestEngine"
	@echo "... JASPTestSync"
	@echo "... QMLComponents"
	@echo "... QMLComponents_resources_1"
	@echo "... QMLComponents_resources_2"
	@echo "... QMLComponents_resources_3"
	@echo "... QMLComponentsplugin"
	@echo "... QMLComponentsplugin_init"
	@echo "... R-Interface"
	@echo "... R-InterfaceNoRInside"
	@echo "... SyntaxInterface"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

