name: Ubuntu

on:
  push:
    branches:
      - development
      - stable

jobs:
  qt:
    name: Ubuntu Build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        qt-version: [6.2]

    steps:
      - name: Cache Qt
        uses: actions/cache@v1  # not v2!
        with:
          path: ../Qt/6.3.1
          key: ${{ runner.os }}-QtCache-Qt6-3
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.3.1'
          install-deps: 'true'
          modules: 'qtwebengine'
          cached: ${{ steps.cache-qt-6-3.outputs.cache-hit }}
          setup-python: 'true'
          tools: ''
          set-env: 'true'
          tools-only: 'false'
      - name: Installing R
        uses: r-lib/actions/setup-r@v2
        with: 
          r-version: '4.2.1'
      - name: Dependencies
        run: |
          sudo apt update
          sudo apt-get -y install build-essential ninja-build libxcb-xkb-dev jags libreadstat-dev libjsoncpp-dev libboost-all-dev mercurial gfortran-9 gfortran-10 flex bison cmake libarchive-dev zlib1g-dev libzstd-dev mesa-utils libglu1-mesa-dev freeglut3-dev mesa-common-dev libglew-dev libglfw3-dev libglm-dev libao-dev libmpg123-dev
      - uses: actions/checkout@v2
      - name: Configure
        run: |
          git submodule update --init
          cmake -S . -B build -D GITHUB_PAT=${{ secrets.GPAT_FOR_JASP }} -DINSTALL_JASP_REQUIRED_LIBRARIES=ON -DLINUX_LOCAL_BUILD=ON -DCUSTOM_R_PATH=/usr/lib/R -GNinja
      - name: Build
        run: cmake --build build
