name: Ubuntu

on:
  push:
    branches:
      - development
      - stable

jobs:
  qt:
    name: Ubuntu Build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        qt-version: [6.2]

    steps:
      - name: Qt Requirements
        run: |
          sudo apt update
      - name: Dependencies
        run: |
          sudo apt-get -y install build-essential qt6-base-dev libjsoncpp-dev libboost-all-dev mercurial gfortran-9 gfortran-10 flex bison r-base cmake libarchive-dev zlib1g-dev libzstd-dev mesa-utils libglu1-mesa-dev freeglut3-dev mesa-common-dev libglew-dev libglfw3-dev libglm-dev libao-dev libmpg123-dev
      - uses: actions/checkout@v2
      - name: Configure
        run: |
          git submodule update --init
          cmake -S . -B build -D GITHUB_PAT=${{ secrets.GPAT_FOR_JASP }} -DINSTALL_JASP_REQUIRED_LIBRARIES=ON -DLINUX_LOCAL_BUILD=ON
      - name: Build
        run: cmake --build build
