name: Windows

on:
  push:
    branches:
      - development
      - stable

jobs:
  qt:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - name: Cache Qt
        uses: actions/cache@v1  # not v2!
        with:
          path: ../Qt/6.3
          key: ${{ runner.os }}-QtCache-Qt6-3
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.3'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          install-deps: 'true'
          modules: 'qtwebengine qtwebenginequick qtcore5compat qtwebchannel qtsql'
          cached: ${{ steps.cache-qt-6-3.outputs.cache-hit }}
          setup-python: 'true'
          tools: ''
          set-env: 'true'
          tools-only: 'false'
      - name: Installing R and Rtools
        uses: r-lib/actions/setup-r@v2
        with: 
          r-version: '4.2.1'
          rtools-version: '42'
      - name: Installing Conan
        run: |
          pip install wheel setuptools
          pip install conan --upgrade
          conan --version
      - name: Configuring Conan Profile
        run: |
          conan profile new default --detect
          conan profile show default
      - uses: actions/checkout@v2
      - name: Configure
        run: |
          git submodule update --init
          cmake -S . -B build -DGITHUB_PAT=${{ secrets.GPAT_FOR_JASP }} -DGITHUB_BUILD=ON
      - name: Building JASP
        run: cmake --build build
